# Generated by Django 4.2.13 on 2024-07-11 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shelf',
            old_name='name',
            new_name='title',
        ),
    ]
