# Generated by Django 4.2.13 on 2024-08-01 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_imageasset_imageasset_unique_book_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='book',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.book'),
        ),
    ]
