# Generated by Django 4.2.13 on 2024-07-11 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_name_shelf_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelf',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
