# Generated by Django 4.2.13 on 2024-07-30 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.book')),
                ('shelf', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.shelf')),
            ],
        ),
        migrations.AddConstraint(
            model_name='imageasset',
            constraint=models.UniqueConstraint(fields=('book',), name='unique_book_image'),
        ),
        migrations.AddConstraint(
            model_name='imageasset',
            constraint=models.UniqueConstraint(fields=('shelf',), name='unique_shelf_image'),
        ),
    ]
