# Generated by Django 4.2.13 on 2024-08-20 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_readingprogress_timestamp_alter_comment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='readingprogress',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
